apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx
  namespace: prod
spec:
  provider: "aws"
  secretObjects:
   - secretName: nginx
     type: Opaque
     data:
       - objectName: "username"
         key: "username"
       - objectName: "password"
         key: "password"
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:us-west-2:1234567890:secret:nginx-test-abcd-efgh
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
